FROM openeuler-20.03-lts:latest

ENV LANG en_US.utf8

ENV SHARDING_VERSION 5.3.1
ENV ZK_VERSION 3.8.0
ENV JRE_VERSION 11.0.12
ENV JRE_HOME /usr/bisheng-jre

COPY apache-shardingsphere-${SHARDING_VERSION}-shardingsphere-proxy-bin.tar.gz .
COPY apache-zookeeper-${ZK_VERSION}-bin.tar.gz .
COPY openEuler_aarch64.repo /etc/yum.repos.d/openEuler_aarch64.repo
COPY gosu-arm64 /usr/local/bin/gosu
COPY bisheng-jre-${JRE_VERSION}-linux-aarch64.tar.gz .

RUN set -eux; \
    yum install -y tar net-tools which shadow hostname && \
    groupadd -g 70 omm;  \
    useradd -u 70 -g omm -d /home/omm omm;  \
    tar -xf apache-shardingsphere-${SHARDING_VERSION}-shardingsphere-proxy-bin.tar.gz -C /usr/local/ && \
    tar -xf apache-zookeeper-${ZK_VERSION}-bin.tar.gz -C /usr/local/ && \
    rm apache-shardingsphere-${SHARDING_VERSION}-shardingsphere-proxy-bin.tar.gz && \
    mv /usr/local/apache-shardingsphere-${SHARDING_VERSION}-shardingsphere-proxy-bin /usr/local/shardingsphere && \
    rm apache-zookeeper-${ZK_VERSION}-bin.tar.gz && \
    mv /usr/local/apache-zookeeper-${ZK_VERSION}-bin /usr/local/zookeeper && \
    tar -xf bisheng-jre-${JRE_VERSION}-linux-aarch64.tar.gz -C /usr/ && \
    mv /usr/bisheng-jre-${JRE_VERSION} /usr/bisheng-jre && \
    rm bisheng-jre-${JRE_VERSION}-linux-aarch64.tar.gz && \
    chown -R omm:omm /usr/local/shardingsphere && \
    chown -R omm:omm /usr/local/zookeeper && \
    chmod -R 755 /usr/local/shardingsphere && \
    chmod -R 755 /usr/local/zookeeper && \
    mkdir -p /var/lib/sharding && mkdir -p /var/log/sharding && \
    chown -R omm:omm /var/log/sharding && chown -R omm:omm /var/log/sharding

ENV GOSU_VERSION 1.12
RUN set -eux; \
     chmod +x /usr/local/bin/gosu

COPY entrypoint.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/entrypoint.sh;ln -s /usr/local/bin/entrypoint.sh /


ENTRYPOINT ["entrypoint.sh"]
CMD ["init"]
