FROM openeuler-20.03-lts:latest

ENV OPENGAUSS_VERSION 5.0.0

COPY openGauss-${OPENGAUSS_VERSION}-openEuler-64bit-all.tar.gz .
COPY gosu-arm64 /usr/local/bin/gosu
COPY gs_createtrust.py .
ENV LANG en_US.utf8
COPY openEuler_aarch64.repo /etc/yum.repos.d/openEuler_aarch64.repo

RUN set -eux; \
    yum install -y bzip2 bzip2-devel curl libaio readline-devel expect tar shadow hostname passwd \
    which git python3 python3-devel openssl-devel net-tools openssh-server vim iputils lsof iproute && \
    groupadd -g 70 omm;  \
    useradd -u 70 -g omm -d /home/omm omm;  \

    mkdir -p /opengauss && \
    chmod 700 /opengauss && \
    mv openGauss-${OPENGAUSS_VERSION}-openEuler-64bit-all.tar.gz /opengauss && \
    mv gs_createtrust.py /opengauss && \
    mkdir -p /volume && \
    chmod -R 755 /volume && \
    chown -R omm:omm /opengauss


ENV LANG en_US.utf8


ENV GOSU_VERSION 1.12
RUN set -eux; \
     chmod +x /usr/local/bin/gosu


COPY entrypoint.sh /usr/local/bin/
COPY entrypoint.sh /usr/local/bin/
COPY install.sh /usr/local/bin/
COPY util.sh /usr/local/bin/
COPY generatexml.py /usr/local/bin/
RUN chmod 755 /usr/local/bin/entrypoint.sh;ln -s /usr/local/bin/entrypoint.sh /
RUN chmod 755 /usr/local/bin/install.sh;ln -s /usr/local/bin/install.sh /
RUN chmod 755 /usr/local/bin/util.sh;ln -s /usr/local/bin/util.sh /

ENTRYPOINT ["entrypoint.sh"]

EXPOSE 5432
