FROM openeuler-20.03-lts:latest

ENV OPENGAUSS_VERSION 6.0.3

COPY openGauss-All-${OPENGAUSS_VERSION}-openEuler20.03-aarch64.tar.gz .
COPY gosu-arm64 /usr/local/bin/gosu
ENV LANG en_US.utf8
COPY openEuler_aarch64.repo /etc/yum.repos.d/openEuler_aarch64.repo

RUN set -eux; \
    yum install -y bzip2 bzip2-devel curl libaio readline-devel expect tar shadow hostname passwd vi \
    which git python3 python3-devel openssl-devel net-tools openssh-server iputils lsof iproute numactl && \
    groupadd -g 70 omm;  \
    useradd -u 70 -g omm -d /home/omm omm;  \
    mkdir -p /var/lib/opengauss && \
    mkdir -p /usr/local/opengauss && \
    chmod 700 /var/lib/opengauss && \
    chmod 700 /usr/local/opengauss && \
    chown -R omm:omm /var/lib/opengauss && \
    chown -R omm:omm /usr/local/opengauss


ENV LANG en_US.utf8


ENV GOSU_VERSION 1.12
RUN set -eux; \
     chmod +x /usr/local/bin/gosu


COPY deploy_cm.sh /usr/local/bin/
COPY entrypoint.sh /usr/local/bin/
COPY install.sh /usr/local/bin/
COPY util.sh /usr/local/bin/
COPY create_trust.sh /usr/local/bin/
COPY generatexml.py /usr/local/bin/
COPY opengauss_role_update.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/entrypoint.sh;ln -s /usr/local/bin/entrypoint.sh /
RUN chmod 755 /usr/local/bin/install.sh;ln -s /usr/local/bin/install.sh /
RUN chmod 755 /usr/local/bin/util.sh;ln -s /usr/local/bin/util.sh /
RUN chmod 755 /usr/local/bin/create_trust.sh;ln -s /usr/local/bin/create_trust.sh /
RUN chmod 755 /usr/local/bin/deploy_cm.sh;ln -s /usr/local/bin/deploy_cm.sh /
RUN chmod 755 /usr/local/bin/opengauss_role_update.sh;ln -s /usr/local/bin/opengauss_role_update.sh /
RUN chmod 755 /usr/local/bin/generatexml.py /

ENTRYPOINT ["entrypoint.sh"]