FROM centos:7.6.1810

ENV OPENGAUSS_VERSION 6.0.0

COPY openGauss-All-${OPENGAUSS_VERSION}-CentOS7-x86_64.tar.gz .
COPY gosu-amd64 /usr/local/bin/gosu
ENV LANG en_US.utf8

RUN set -eux; \
    yum install -y bzip2 bzip2-devel curl libaio readline-devel expect \
    which git python3 python3-devel openssl-devel net-tools openssh-server vim && \
    groupadd -g 70 omm;  \
    useradd -u 70 -g omm -d /home/omm omm;  \

    mkdir -p /opengauss && \
    chmod 700 /opengauss && \
    mv openGauss-All-${OPENGAUSS_VERSION}-CentOS7-x86_64.tar.gz /opengauss && \
    mkdir -p /volume && \
    chmod -R 755 /volume && \
    chown -R omm:omm /opengauss


ENV LANG en_US.utf8


ENV GOSU_VERSION 1.12
RUN set -eux; \
     chmod +x /usr/local/bin/gosu


COPY entrypoint.sh /usr/local/bin/
COPY entrypoint.sh /usr/local/bin/
COPY install.sh /usr/local/bin/
COPY util.sh /usr/local/bin/
COPY create_trust.sh /usr/local/bin/
COPY generatexml.py /usr/local/bin/
RUN chmod 755 /usr/local/bin/entrypoint.sh;ln -s /usr/local/bin/entrypoint.sh /
RUN chmod 755 /usr/local/bin/install.sh;ln -s /usr/local/bin/install.sh /
RUN chmod 755 /usr/local/bin/util.sh;ln -s /usr/local/bin/util.sh /
RUN chmod 755 /usr/local/bin/create_trust.sh;ln -s /usr/local/bin/create_trust.sh /
RUN chmod 755 /usr/local/bin/generatexml.py /

ENTRYPOINT ["entrypoint.sh"]

EXPOSE 5432
